[[rules]]
  id = "generic-api-key"
  description = "Detected a Generic API Key, potentially exposing access to various services and sensitive operations."
  regex = '''(?i)(?P<key>[a-z0-9-_\.]{8,64})(?:['|"]?:\s?['|"]?)(?P<secret>[a-z0-9-_\.]{8,128})['|"]?'''
  entropy = 3.5

    [[rules.allowlists]]
      description = "Allow HDG Boiler node IDs in the definitions.py file"
      paths = ['''custom_component/hdg_boiler/definitions\.py''']
      regexes = [
          '''[0-9]+T''',
      ]

    [[rules.allowlists]]
      description = "Allow specific config keys in const.py for polling group definitions"
      paths = ['''custom_components/hdg_boiler/const\.py''']
      # This targets the values of "config_key" in POLLING_GROUP_DEFINITIONS
      regexes = [
          '''^scan_interval_group_\d+_[a-z_]+$'''
      ]

    [[rules.allowlists]]
      description = "Allow translation_key assignments in const.py"
      paths = ['''custom_components/hdg_boiler/const\.py''']
      # This targets the values of "translation_key" if they were in const.py (which they are not based on current structure)
      # Keeping it general for now, but might be too broad or unnecessary if translation_keys are only in definitions.py
      regexes = [
          '''^[a-z0-9_]+$''' # Matches generic key-like strings
      ]

    [[rules.allowlists]]
      description = "Allow scan interval translation keys in de.json"
      paths = ['''custom_components/hdg_boiler/translations/de\.json''']
      regexes = [
          '''^scan_interval_group_\d+_[a-z_]+$''' # Matches the keys themselves
      ]

    [[rules.allowlists]]
      description = "Allow specific translation_key values in definitions.py"
      paths = ['''custom_components/hdg_boiler/definitions\.py''']
      # This regex targets the values of "translation_key"
      regexes = ['''^[a-z0-9_]+$''']

# Global allowlist to ignore specific known false positives from HdgSetValueWorker logs
[allowlist]
    description = "Allow specific HdgSetValueWorker log patterns that are misidentified as secrets by generic rules."
    # These regexes match the beginning of log lines that were being flagged.
    # The 'paths' entry restricts these allowlist regexes to only apply to the specified file,
    # preventing accidental allowlisting of similar patterns in other files.
    paths = ['''custom_components/hdg_boiler/classes/set_value_worker\.py''']
    regexes = [
        # Matches: HdgSetValueWorker: Calculated wait_timeout: ...
        '''^HdgSetValueWorker: Calculated wait_timeout:.*''',
        # Matches: HdgSetValueWorker: Collected N items to process: [...]
        '''^HdgSetValueWorker: Collected \d+ items to process: \[.*\]''',
        # Matches: HdgSetValueWorker: _process_collected_items: No items to process.
        '''^HdgSetValueWorker: _process_collected_items: No items to process\.''',
        # Matches: HdgSetValueWorker: _process_collected_items: Processing N items: [...]
        '''^HdgSetValueWorker: _process_collected_items: Processing \d+ items: \[.*\]'''
    ]
