repos:
  # Standard hooks for file integrity and basic checks.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Ruff hook for fast linting and formatting.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # mypy hook for static type checking.
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.16.1"
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --explicit-package-bases]
        additional_dependencies: []

  # Sourcery hook for AI-powered refactoring.
  - repo: https://github.com/sourcery-ai/sourcery
    rev: "v1.37.0"
    hooks:
      - id: sourcery
        # Automatically apply fixes suggested by Sourcery
        args: ["--fix"]

  # Gitleaks hook for detecting secrets and sensitive information.
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.2 # Use the latest stable version
    hooks:
      - id: gitleaks
