# Main configuration file for the Ruff linter and formatter.
# The selection of rules is inspired by Home Assistant Core's configuration
# to ensure high code quality and consistency with HA development standards.

target-version = "py312"

# See https://docs.astral.sh/ruff/rules/ for all rules.
[lint]
select = [
    "B007",      # Loop control variable not used within loop body
    "B014",      # Duplicate exception in handler
    "C",         # McCabe complexity
    "D",         # Docstrings
    "E",         # pycodestyle errors
    "F",         # Pyflakes
    "ICN001",    # import conventions
    "PGH004",    # Use specific rule codes when using noqa
    "PLC0414",   # Useless import alias
    "SIM105",    # Use contextlib.suppress for try-except-pass
    "SIM117",    # Merge with-statements
    "SIM118",    # Use 'in' for dictionary keys
    "SIM201",    # Use '!=' instead of 'not ... =='
    "SIM212",    # Use ternary operator
    "SIM300",    # Yoda conditions
    "SIM401",    # Use dict.get with default
    "T20",       # flake8-print
    "TRY004",    # Prefer TypeError for invalid type
    "RUF006",    # Store asyncio.create_task return value
    "UP",        # pyupgrade
    "W",         # pycodestyle warnings
]

# Rules to ignore globally.
ignore = [
    "D202",      # No blank lines allowed after function docstring
    "D203",      # 1 blank line required before class docstring
    "D213",      # Multi-line docstring summary should start at the second line
    "D404",      # First word of the docstring should not be "This"
    "D406",      # Section name should end with a newline
    "D407",      # Section name underlining
    "D411",      # Missing blank line before section
    "E501",      # Line too long (handled by formatter)
    "E731",      # Do not assign a lambda expression, use a def
]

# --- Sub-configurations for the lint section ---

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.pyupgrade]
# Helps with compatibility for older Python versions if needed.
keep-runtime-typing = true

# Configuration for McCabe complexity checker.
[lint.mccabe]
max-complexity = 25
