name: CI & Validation

on:
  push:
    branches:
      - main
      - dev
      - release-test
  pull_request:
    branches:
      - main
      - dev
      - release-test

jobs:
  lint-and-test:
    name: Lint, Test, Validate
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && !contains(github.event.head_commit.message, 'Merge pull request'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies (mit pre-commit)
        run: |
          pip install pre-commit
          pre-commit install-hooks

      - name: Run pre-commit checks (Linting, Formatting, Mypy)
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Run Sourcery review
        uses: sourcery-ai/action@v1
        with:
          token: ${{ secrets.SOURCERY_TOKEN }}
          check: true

  hassfest:
    name: "Hassfest Validation"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Run hassfest validation"
        uses: "home-assistant/actions/hassfest@master"

  hacs:
    name: "HACS Validation"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Run HACS validation"
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: "brands"
