# This workflow runs on every push to the 'dev' branch.
# Its sole purpose is to run all quality assurance checks (linting,
# type checking, and validation) to ensure the development branch
# remains stable and clean. It does NOT perform any release steps.

name: "Dev Branch Checks"

on:
  push:
    branches:
      - 'dev'

jobs:
  # Job 1: Call the reusable linting, type-checking, and refactoring workflow.
  linting:
    name: "Run Linter, Type-Checker & Sourcery"
    uses: ./.github/workflows/lint.yml

  # Job 2: Call the reusable HACS and hassfest validation workflow.
  validation:
    name: "Run HACS & Hassfest Validation"
    uses: ./.github/workflows/validate.yml
