name: Semantic Release (Test)

on:
  push:
    branches:
      - release-test

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Create Test Release
    runs-on: ubuntu-latest
    if: github.repository_owner == 'banter240' && github.ref == 'refs/heads/release-test'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Python Semantic Release
        run: |
          pip install python-semantic-release

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release publish
